#' fgsea wrapper
#'
#' This function is a convenient wrapper for the
#' \code{\link[=fgsea]{fgsea::fgsea()}} function.
#'
#' @inheritParams .decoupler_mat_format
#' @inheritParams .decoupler_network_format
#' @param options A list of named options to pass to
#' \code{\link[=fgsea]{fgsea::fgsea()}}..
#' These options should not \code{include}, \code{pathways} or \code{stats}.
#' @param seed A single value, interpreted as an integer, or NULL.
#'
#' @return A long format tibble of the enrichment scores for each tf
#'  across the conditions. Resulting tibble contains the following columns:
#'  \enumerate{
#'    \item{\code{statistic}}: {Indicates which method is associated with which score.}
#'    \item{\code{tf}}: {Source nodes of \code{network}.}
#'    \item{\code{condition}}: {Condition representing each column of \code{mat}.}
#'    \item{\code{score}}: {Regulatory activity (enrichment score).}
#'    \item{\code{...}}: {Columns of metadata generated by fgsea method.}
#'  }
#' @export
#' @importFrom fgsea fgsea
run_fgsea <- function(mat,
                      network,
                      .source = .data$tf,
                      .target = .data$target,
                      force_ties = F,
                      options = list(),
                      seed = 42) {
  # Check for NAs/Infs in mat
  check_nas_infs(mat)

  regulons <- network %>%
    convert_to_fgsea({{ .source }}, {{ .target }})

  conditions <- colnames(mat) %>%
    set_names()

  set.seed(seed)
  map_dfr(.x = conditions, .f = ~ {
    stats <- mat[, .x]
    options <- c(list(pathways = regulons, stats = stats), options)
    result <- do.call(what = fgsea, args = options)
    if (all(table(stats) == 1) | force_ties){
      result
    } else {
      warning('
      Ties were detected, NA will be returned.
      To force ties use force_ties = T, but results might not be reproducible.')
      result %>% mutate(across(!pathway, function(x){NA}))
    }
  }, .id = "condition") %>%
    mutate(statistic = "fgsea") %>%
    select(.data$statistic, tf = .data$pathway, .data$condition, score = .data$ES, everything()) %>%
    as_tibble() %>%
    `attr<-`(".internal.selfref", NULL)
}
