#' Fast Gene Set Enrichment Analysis (FGSEA)
#'
#' @description
#' Calculates regulatory activities using FGSEA.
#'
#' @details
#' This function is a wrapper for the method \code{\link[=fgsea]{fgsea::fgsea()}}.
#'
#' @inheritParams .decoupler_mat_format
#' @inheritParams .decoupler_network_format
#' @param force_ties Whether to force ties or not (results might not be
#' reproducible in all systems).
#' @param times How many permutations to do?
#' @param nproc Number of cores to use for computation.
#' @param seed A single value, interpreted as an integer, or NULL.
#'
#' @return A long format tibble of the enrichment scores for each source
#'  across the conditions. Resulting tibble contains the following columns:
#'  \enumerate{
#'    \item{\code{statistic}}: {Indicates which method is associated with which score.}
#'    \item{\code{source}}: {Source nodes of \code{network}.}
#'    \item{\code{condition}}: {Condition representing each column of \code{mat}.}
#'    \item{\code{score}}: {Regulatory activity (enrichment score).}
#'    \item{\code{...}}: {Columns of metadata generated by fgsea method.}
#'  }
#' @family decoupleR statistics
#' @export
#' @examples
#' inputs_dir <- system.file("testdata", "inputs", package = "decoupleR")
#'
#' mat <- readRDS(file.path(inputs_dir, "input-expr_matrix.rds"))
#' network <- readRDS(file.path(inputs_dir, "input-dorothea_genesets.rds"))
#'
#' run_fgsea(mat, network, .source='tf', force_ties = T)
run_fgsea <- function(mat,
                      network,
                      .source = .data$source,
                      .target = .data$target,
                      force_ties = T,
                      times = 100,
                      nproc = 4,
                      seed = 42,
                      ...) {
  # Check for NAs/Infs in mat
  check_nas_infs(mat)

  regulons <- network %>%
    convert_to_fgsea({{ .source }}, {{ .target }})

  conditions <- colnames(mat) %>%
    set_names()

  set.seed(seed)
  map_dfr(.x = conditions, .f = ~ {
    stats <- mat[, .x]
    options <- list(
      pathways = regulons,
      stats = stats,
      nPermSimple = times,
      nproc = nproc
      )
    result <- suppressWarnings(do.call(what = fgsea::fgsea, args = options))
    if (all(table(stats) == 1) | force_ties){
      result
    } else {
      warning('
      FGSEA: Ties were detected, NAs will be returned.
      To force ties use force_ties = T, but results might not be reproducible.')
      result %>% mutate(across(!pathway, function(x){NA}))
    }
  }, .id = "condition") %>%
    select(.data$pathway, .data$condition, .data$ES, .data$NES, .data$pval) %>%
    tidyr::pivot_longer(cols=c("ES","NES"), names_to ="statistic", values_to="score") %>%
    mutate(statistic=if_else(statistic=='ES', 'fgsea', 'norm_fgsea')) %>%
    rename('source'=pathway, 'p_value'=pval) %>%
    select(statistic, source, condition, score, p_value) %>%
    mutate(score = replace_na(score, 0))
}
